#!/usr/bin/env bash
# Test count for the README — generated here, never typed by hand (STANDARDS §3).
# Reads the JUnit XML reports Gradle writes to build/test-results/test.
#
#   scripts/test_count.sh            # run the tests, then count
#   scripts/test_count.sh --no-run   # count the reports from the last run (used in CI)
set -euo pipefail

reports_dir="build/test-results/test"

if [[ "${1:-}" != "--no-run" ]]; then
  echo "running ./gradlew test ..." >&2
  ./gradlew test --console=plain >/dev/null
fi

if ! compgen -G "$reports_dir/TEST-*.xml" > /dev/null; then
  echo "no JUnit reports in $reports_dir — run ./gradlew test first" >&2
  exit 1
fi

read -r tests failures errors skipped classes < <(
  awk '
    /<testsuite / {
      classes++
      if (match($0, /tests="[0-9]+"/))    { tests    += substr($0, RSTART + 7,  RLENGTH - 8) }
      if (match($0, /failures="[0-9]+"/)) { failures += substr($0, RSTART + 10, RLENGTH - 11) }
      if (match($0, /errors="[0-9]+"/))   { errors   += substr($0, RSTART + 8,  RLENGTH - 9) }
      if (match($0, /skipped="[0-9]+"/))  { skipped  += substr($0, RSTART + 9,  RLENGTH - 10) }
    }
    END { printf "%d %d %d %d %d\n", tests, failures, errors, skipped, classes }
  ' "$reports_dir"/TEST-*.xml
)

passed=$((tests - failures - errors - skipped))

echo "- **Tests: $tests in $classes classes — $passed passed, $failures failed, $errors errored, $skipped skipped**"
echo "  <sub>generated by \`scripts/test_count.sh\` from \`build/test-results/test\`</sub>"
